### ISSUE TITLE
The plugin fails to load if pytest-xdist is installed but not loaded

### ISSUE THREAD

**Issue by mgorny** [pytest-dev/pytest-rerunfailures#177]
The plugin code seems to assume that the `xdist` plugin will be enabled if `xdist.newhooks` import succeeds. However, if `xdist` is not loaded for some reason (e.g. is explicitly disabled), then the assumption is incorrect and pytest crashes.

This can be easily reproduced using rerunfailures' own test suite:

```pytb
$ tox -e py310 -- -p no:xdist
GLOB sdist-make: /tmp/pytest-rerunfailures/setup.py
py310 create: /tmp/pytest-rerunfailures/.tox/py310
py310 installdeps: pytest-xdist
py310 inst: /tmp/pytest-rerunfailures/.tox/.tmp/package/1/pytest-rerunfailures-10.3.dev0.zip
py310 installed: attrs==21.4.0,execnet==1.9.0,iniconfig==1.1.1,packaging==21.3,pluggy==1.0.0,py==1.11.0,pyparsing==3.0.7,pytest==6.2.5,pytest-forked==1.4.0,pytest-rerunfailures @ file:///tmp/pytest-rerunfailures/.tox/.tmp/package/1/pytest-rerunfailures-10.3.dev0.zip,pytest-xdist==2.5.0,toml==0.10.2
py310 run-test-pre: PYTHONHASHSEED='4057923354'
py310 run-test: commands[0] | pytest test_pytest_rerunfailures.py -p no:xdist
========================================================= test session starts =========================================================
platform linux -- Python 3.10.2, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
cachedir: .tox/py310/.pytest_cache
rootdir: /tmp/pytest-rerunfailures
plugins: rerunfailures-10.3.dev0, xdist-2.5.0, forked-1.4.0
collected 63 items                                                                                                                    
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/tmp/pytest-rerunfailures/.tox/py310/lib/python3.10/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/tmp/pytest-rerunfailures/.tox/py310/lib/python3.10/site-packages/_pytest/main.py", line 322, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/tmp/pytest-rerunfailures/.tox/py310/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/tmp/pytest-rerunfailures/.tox/py310/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/tmp/pytest-rerunfailures/.tox/py310/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/tmp/pytest-rerunfailures/.tox/py310/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/tmp/pytest-rerunfailures/.tox/py310/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/tmp/pytest-rerunfailures/.tox/py310/lib/python3.10/site-packages/_pytest/main.py", line 333, in pytest_collection
INTERNALERROR>     session.perform_collect()
INTERNALERROR>   File "/tmp/pytest-rerunfailures/.tox/py310/lib/python3.10/site-packages/_pytest/main.py", line 636, in perform_collect
INTERNALERROR>     self.config.pluginmanager.check_pending()
INTERNALERROR>   File "/tmp/pytest-rerunfailures/.tox/py310/lib/python3.10/site-packages/pluggy/_manager.py", line 262, in check_pending
INTERNALERROR>     raise PluginValidationError(
INTERNALERROR> pluggy._manager.PluginValidationError: unknown hook 'pytest_configure_node' in plugin <module 'pytest_rerunfailures' from '/tmp/pytest-rerunfailures/.tox/py310/lib/python3.10/site-packages/pytest_rerunfailures.py'>

======================================================== no tests ran in 0.05s ========================================================
ERROR: InvocationError for command /tmp/pytest-rerunfailures/.tox/py310/bin/pytest test_pytest_rerunfailures.py -p no:xdist (exited with code 3)
_______________________________________________________________ summary _______________________________________________________________
ERROR:   py310: commands failed
```

I have reported a similar problem in SQLAlchemy, and they have devised a nice solution using `config.pluginmanager.hasplugin()`: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3555/1/lib/sqlalchemy/testing/plugin/pytestplugin.py

**Comment by icemac** [comment]
Thank you for reporting this issue. A PR is welcome.
