### ISSUE TITLE
pytest_handlecrashitem faults with NotImplementedError when using the loadgroup  test distribution algorithm

### ISSUE THREAD

**Issue by hb2638** [pytest-dev/pytest-rerunfailures#247]
I'm using xdist with the --dist loadgroup command line option and the reruns are not working for crashed nodes because xdist's LoadScopeScheduling.mark_test_pending for throws a NotImplementedError error @ https://github.com/pytest-dev/pytest-xdist/blob/master/src/xdist/scheduler/loadscope.py#L244

[gw2] node down: Not properly terminated
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/_pytest/main.py", line 271, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/_pytest/main.py", line 325, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/pluggy/_hooks.py", line 493, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/pluggy/_manager.py", line 115, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/pluggy/_callers.py", line 152, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/pluggy/_result.py", line 114, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/pluggy/_callers.py", line 77, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/xdist/dsession.py", line 123, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/xdist/dsession.py", line 148, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/xdist/dsession.py", line 217, in worker_errordown
INTERNALERROR>     self.handle_crashitem(crashitem, node)
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/xdist/dsession.py", line 382, in handle_crashitem
INTERNALERROR>     self.config.hook.pytest_handlecrashitem(
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/pluggy/_hooks.py", line 493, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/pluggy/_manager.py", line 115, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/pluggy/_callers.py", line 113, in _multicall
INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/pluggy/_callers.py", line 77, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/pytest_rerunfailures.py", line 351, in pytest_handlecrashitem
INTERNALERROR>     sched.mark_test_pending(crashitem)
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/xdist/scheduler/loadscope.py", line 245, in mark_test_pending
INTERNALERROR>     raise NotImplementedError()
INTERNALERROR> NotImplementedError
= 4 failed, 1155 passed, 286 skipped, 87 warnings, 10 rerun in 4137.10s (1:08:57) =

**Comment by icemac** [comment]
Thank you for your PR. I do not know anything about the `loadgroup` test distribution algorithm.
So a PR is welcome to fix this issue.

**Comment by msabramo** [comment]
I have this traceback too. In our case we use the pytest-xdist `loadfile` scheduler.

Does the workaround from @pich02 work? I imagine that might make the error go away but might not be ideal. If it is as simple as that and `mark_test_pending` is not that important, then I imagine I could submit a PR that checks the method exists before calling it. But is it really that simple?

**Comment by msabramo** [comment]
Hmmm I just tried out the approach @pich02 mentioned and I think it prevents the error but then my tests never complete, so I don't think that is a solution.

**Comment by msabramo** [comment]
I do want to experiment with #309 and see if it works. It's difficult for me at the moment though because the project I'm seeing this with is currently stuck with an old version of pytest. If anyone is able to test out the change at #309 and comment, it would be much appreciated.
