### ISSUE TITLE
Running tox doesn't find CHANGES.rst

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-rerunfailures#35]
When I try to run tox locally, I get:

```
ERROR: actionid: py34-pytest29
msg: installpkg
cmdargs: [local('/home/florian/proj/pytest-rerunfailures/.tox/py34-pytest29/bin/pip'), 'install', '-U', '--no-deps', '/home/florian/proj/pytest-rerunfailures/.tox/dist/pytest-rerunfailures-2.0.1.dev0.zip']
env: [...]

Processing ./.tox/dist/pytest-rerunfailures-2.0.1.dev0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-vcr7ysj5-build/setup.py", line 9, in <module>
        open('CHANGES.rst').read()),
    FileNotFoundError: [Errno 2] No such file or directory: 'CHANGES.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-vcr7ysj5-build/
```

I have *no idea* why this happens. I really can't figure it out. I'm in the correct directory (found out by using `os.getcwd()` as filename :laughing:), `README.rst` could be read, `CHANGES.rst` is there (and I can read it)...

strace says:

```
[pid 18070] open("README.rst", O_RDONLY|O_CLOEXEC) = 4
[pid 18070] open("CHANGES.rst", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

**Comment by tomviner** [comment]
Here's why:

```bash
$ python setup.py sdist | egrep "README|CHANGE"
copying README.rst -> pytest-rerunfailures-2.0.1.dev0
```

And here's the fix:
```bash
$ pip install check-manifest
$ check-manifest -c
...
creating MANIFEST.in
$ python setup.py sdist | egrep "README|CHANGE"

copying CHANGES.rst -> pytest-rerunfailures-2.0.1.dev0
copying README.rst -> pytest-rerunfailures-2.0.1.dev0
```

PR https://github.com/pytest-dev/pytest-rerunfailures/pull/37

**Comment by florianpilz** [comment]
Ah, that's how it's done! In commits 41b25be57ffa317bea075cd60176b20902c68906 and 26bba18ac5e54e75990949182b4cc5389e58eeb6 you can see that I struggled with that one myself. :>
