### ISSUE TITLE
PluginValidationError:

### ISSUE THREAD

**Issue by anu565lol** [pytest-dev/pytest-rerunfailures#91]
I am facing a plugin validation error. 

$ pytest --reruns 5
Traceback (most recent call last):
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 510, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vizzbee/anaconda3/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/_pytest/config.py", line 49, in main
    config = _prepareconfig(args, plugins)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/_pytest/config.py", line 168, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/_pytest/helpconfig.py", line 68, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/_pytest/config.py", line 957, in pytest_cmdline_parse
    self.parse(args)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/_pytest/config.py", line 1121, in parse
    self._preparse(args, addopts=addopts)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/_pytest/config.py", line 1084, in _preparse
    self.pluginmanager.load_setuptools_entrypoints('pytest11')
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 515, in load_setuptools_entrypoints
    "Plugin %r could not be loaded: %s!" % (ep.name, e))
_pytest.vendored_packages.pluggy.PluginValidationError: Plugin 'rerunfailures' could not be loaded: (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'))!

$ pip list|grep rerunfailures
pytest-rerunfailures                7.0

**Comment by icemac** [comment]
It seems you are using pytest 3.2.1 which is too old for pytest-rerunfailures 7.0.
